specVersion: "0.0.1"
description: "This subquery indexes which block a given extrinsic is finalized in"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler





